### ISSUE TITLE
Type "TabNine::" where?

### ISSUE THREAD

**Issue by jarmo** [zxqfl/tabnine-vim#17]
In FAQ and in the completion window itself TabNine says to me that I need to type either this or that (for example `TabNine::version` or `TabNine::sem`). If I try to type these or similar commands anywhere then I will receive an error message that this command does not exist or something similar. Where shall I type these in Vim?

**Comment by zxqfl** [comment]
Sorry for the unclear instructions. You should enter insert mode and type it directly into the buffer.

**Comment by jarmo** [comment]
I tried that, but nothing happened when I typed `TabNine::version` or `TabNine::sem`. Should I also exit insert mode or anything else?

**Comment by Shougo** [comment]
When you typed `TabNine::version` or `TabNine::sem` in buffer, the candidate is suggested.

**Comment by jarmo** [comment]
Managed to get it work - problem was that it was part of a previous word, particularly ```[TabNine::ver```. As soon as I entered it separately it started to work.

**Comment by zxqfl** [comment]
Glad it worked!

**Comment by jarmo** [comment]
I don't know if there's anything to do about it, but maybe TabNine can understand that it should not suggest to type `TabNine::sem` when it will not actually work or it should work whenever it is typed.

I'm not sure if this is a bug, which can be easily fixed or not, but my initial problem was that TabNine suggested me something and even if I typed it then nothing happened.

Maybe reopen it until it's understood if it could be fixed in either of the way?

**Comment by zxqfl** [comment]
It's actually intended to work whenever it's typed. Here's what it does on my machine:

![image](https://user-images.githubusercontent.com/11807870/52976262-c4b7c680-3396-11e9-83dd-0f9dddda1fd6.png)

**Comment by pvonmoradi** [comment]
Can I enable/disable `TabNine::sem` with a vim command so I can assign a keybinding to it?  
Writing a configuration line directly inside the source buffer seems unorganized.
