### ISSUE TITLE
Exit out of suggestions window and go back to original text

### ISSUE THREAD

**Issue by himat** [zxqfl/tabnine-vim#28]
Is it possible to have a key to exit the tabnine auto suggestions window, and then to go back to the original text that was there before any `tab` keys were pressed?

Ex.
![image](https://user-images.githubusercontent.com/1156974/62226406-2b023580-b388-11e9-9d6f-77939c9f23f0.png)
and then I press `tab` a few times
![image](https://user-images.githubusercontent.com/1156974/62226439-3bb2ab80-b388-11e9-84c4-9310efea039b.png)
I now want to be able to press something like escape that removes the suggestions list and reset the text back to just `loss_`. If I press `escape` right now, then it removes the suggestions list, goes into normal mode, and leaves the text as `loss_names` instead of the original `loss`.

**Comment by zxqfl** [comment]
Try Ctrl+y

**Comment by himat** [comment]
That only gets rid of the menu, it doesn't reset back to the text that was there previously.
