### ISSUE TITLE
<Esc> doesn't cancel completion and return to normal mode

### ISSUE THREAD

**Issue by jaydorsey** [zxqfl/tabnine-vim#5]
I haven't used YCM before, so I don't know if this is intended behavior, but I expect the <esc> key to cancel the completion when using tabnine.

Example:

I have a small def/end block I created, and I need a single word inside the def/end, which I've typed out completely (because it wasn't very long). I'm still in insert mode and the dropdown is displayed but now I want to leave insert mode. 

I can't leave insert mode because the autocomplete prevents the <esc> key from switching modes.

I don't want to press <enter> because that inserts a new line (which I have to delete).

I don't want to press <tab> because that cycles me thru the dropdown (to a word I don't want).

```
def foo
  import<cursor is here and autocomplete shows up>
end
```

If I want to exit insert mode, so I can navigate with my hjkl keys again I'd normally press <esc> key.
However, <esc> key makes the completion window flash for a brief moment (a screen refresh) and then returns

![image](https://user-images.githubusercontent.com/191564/48134379-c0442380-e267-11e8-8828-4bdb5cdbee25.png)

Expected behavior: A single <esc> press should cancel the auto-complete dropdown. A 2nd <esc> would put me back into normal mode.

It looks like <ctrl-c> will cancel the dropdown and return me to normal mode. Would be nice if <esc> would at least cancel the menu.

Update: Also, looks like <ctrl-c> isn't even a recommended way to cancel the autocomplete. https://github.com/Valloric/YouCompleteMe#i-get-weird-errors-when-i-press-ctrl-c-in-vim. Also, per the linked comment it sounds like <esc> in YCM is supposed to exit autocomplete mode, so I think this is a bug, rather than a feature request.

# Diagnostic data

## OS version, distribution, etc.

Macos 10.14, nvim 0.3.1

**Comment by anowlcalledjosh** [comment]
What happens if you add `<esc>` to `g:ycm_key_list_stop_completion`?

i.e. add something like this to your vimrc:

```vim
let g:ycm_key_list_stop_completion += ['<esc>']
```

Alternatively, c-y is in that list [by default](https://github.com/Valloric/YouCompleteMe#the-gycm_key_list_stop_completion-option), so you should be able to press control-Y to dismiss the popup.

**Comment by jaydorsey** [comment]
@anowlcalledjosh Thanks for the suggestion. I added that but received an error `E121: Undefined variable: g:ycm_key_list_stop_completion` when I opened nvim again.

**Comment by jaydorsey** [comment]
@anowlcalledjosh After some research, I went back and tried your command as `let g:ycm_key_list_stop_completion = ['<c-y', '<esc>']` and that worked (I dropped the + and assigned the list myself).

I'm going to close this issue because that resolved the problem for me (even if it's not the default). Thank you!
